language: python

matrix:
    include:
        - os: linux
          python: "2.7"
        - os: linux
          python: "3.4"
        - os: linux
          python: "3.5"
        - os: linux
          python: "3.6"
        - os: osx
          language: generic

          install:
              - sudo apt-get update
              - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
                wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
                else
                wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
                fi
              - bash miniconda.sh -b -p $HOME/miniconda
              - export PATH="$HOME/miniconda/bin:$PATH"
              - hash -r
              - conda config --set always_yes yes --set changeps1 no
              - conda update -q conda
                # Useful for debugging any issues with conda
              - conda info -a
              - conda install torch
              - pip install coverage coveralls
              - pip install .

          script:
              - coverage run --source=cudnnenv setup.py test
              - pip install flake8 && flake8

          after_success:
              - coveralls
